# Generated by Django 5.0.4 on 2024-04-16 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acesso', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sexo',
            name='sexo',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=256),
        ),
    ]
