# Generated by Django 5.0.4 on 2024-04-16 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acesso', '0002_alter_sexo_sexo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professor',
            name='sexo',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=256),
        ),
        migrations.DeleteModel(
            name='Sexo',
        ),
    ]
